version: "3"

tasks:
    build:
        desc: Build the app
        cmds:
        - GOFLAGS=-mod=mod go build -o bin/investment-manager main.go 

    run: 
        desc: Run the app
        cmds:
        - GOFLAGS=-mod=mod go run main.go
    
    build-server:
        desc: Build the server
        cmds:
        - GOFLAGS=-mod=mod go build -o bin/server server/main/server.go
